openapi: 3.0.1

info:
  title: snmp-browser project
  description: snmp-browser OpenAPI specification
  version: '1.0.0'

externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io

servers:
  - url: http://localhost:8080/

tags:
  - name: SNMP
    description: Operations with SNMP

paths:
  /snmp/get:
    post:
      tags:
        - SNMP
      summary: Returns result of SNMP GET method
      requestBody:
        description: Parameters to perform SNMP GET request
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SnmpRequest'
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SnmpGetResponse'
        400:
          description: On client error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseError'
        500:
          description: On server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseError'

  /snmp/walk:
    post:
      tags:
        - SNMP
      summary: Returns result of SNMP WALK method
      requestBody:
        description: Parameters to perform SNMP WALK request
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SnmpRequest'
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SnmpWalkResponse'

components:
  schemas:

    SnmpRequest:
      type: object
      required:
        - method
        - targetHostname
        - oids
      properties:
        method:
          enum:
            - GET
            - WALK
          example: GET
        targetHostname:
          type: string
          example: "1.1.1.1"
        oids:
          type: array
          items:
            type: string
            example: ['1.3.6.1.2.1.1.1.0', '1.3.6.1.2.1.1.4.0']
        communities:
          type: array
          items:
            type: string
            example: ['public', 'private']
            default: ['public']
        port:
          type: integer
          example: 161
          default: 161
        version:
          enum:
            - VERSION1
            - VERSION2C
          example: VERSION2C
          default: VERSION2C
        timeout:
          type: integer
          description: "request timeout in seconds"
          example: 15
          default: 5
        retries:
          type: integer
          description: "request number of retries"
          example: 3
          default: 0

    SnmpGetResponse:
      type: object
      properties:
        results:
          type: array
          items:
            type: object
            properties:
              oid:
                type: string
              type:
                type: string
              value:
                type: string

    SnmpWalkResponse:
      type: object
      properties:
        results:
          type: array
          items:
            type: object
            properties:
              oid:
                type: string
              type:
                type: string
              value:
                type: string

    ResponseError:
      type: object
      required:
        - message
      properties:
        message:
          type: string
          example: 'Error: request timeout'
